/*
 * in stdlib library there is a function named srand() is used for generating random number and it takes a value known as seed to generate number between 0 to seed, for every time iteration ( call) to get different value we can pass time() function with NULL as time()'s parameter to get return time in seconds, as time grow forward, every time we will get different random number
 */
/*
 * and rand() function is used to return the random value generated by the srand() fumction
 *
 */
/*
 * rock, paper scissors
 * player 1: rock
 * player 2(computer): scissors --> player 1 get 1 points.
 * rock vs scissors ==> rock
 * paper vs scissors ==> scissors
 * rock vs paper ==> paper
 *
 */
/*
 * allow user to play this game with computer, log the score of the player and computer and display the name of the winner at the end
 */
/*
 * you have to display the name of the player during gameplay, take input from the user
 */

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int genRandomNum(int n) {
    srand(time(NULL));
    return rand() % n;
}

int main()
{
    int num = 5;
    printf("Random number between 0 to %d: %d\n", num, genRandomNum(num));    
    return 0;
}

